---

- name: Create Script Dir
  file:
    path: /usr/local/websoft9
    state: directory

- name: Install module
  pip:
    name: pyinotify

- name: Copy Script
  copy:
    src: main.py
    dest: /usr/local/websoft9
    mode: 0770

- name: Configuration Service
  template:
    src: auto_chown.service
    dest: /etc/systemd/system


- name: started service
  service: name=auto_chown state=started enabled=yes

- name: Setting File Permission
  shell: find /data/* -type f -exec chmod 640 {} \;

- name: Setting Directory Permission
  shell: find /data/* -type d -exec chmod 750 {} \;

- name: Seting Owner and Group for Nginx
  shell: chown -R nginx. {{item}}
  with_items:
    - /data/wwwroot
    - /data/apps

- name: Seting Owner and Group for MySQL
  shell: chown -R mysql. /data/mysql
  