---
- name: Create apps directory
  file: 
      path: /data/apps
      state: directory
      owner: nginx
      group: nginx

- name: Dowload phpMyAdmin
  unarchive:
    src: https://files.phpmyadmin.net/phpMyAdmin/4.0.10.20/phpMyAdmin-4.0.10.20-all-languages.zip
    dest: /data/apps
    remote_src: yes
  when: phpver == 54

- name: Dowload phpMyAdmin
  unarchive:
    src: https://files.phpmyadmin.net/phpMyAdmin/4.8.2/phpMyAdmin-4.8.2-all-languages.zip
    dest: /data/apps
    remote_src: yes
  when: phpver != 54



- name: phpMyadmin directory rename
  shell: mv /data/apps/phpMyAdmin-* /data/apps/phpmyadmin
 

- name: phpMyadmin Configuration
  copy: 
    src: config.inc.php
    dest: /data/apps/phpmyadmin/


- name: Active phpMyAdmin 4.0.x Advanced Features
  mysql_db:
    config_file: /etc/my.cnf
    login_user: root
    login_password: 123456
    name: phpmyadmin
    state: import
    target: /data/apps/phpmyadmin/examples/create_tables.sql
  when: phpver == 54


- name: Active phpMyAdmin 4.x Advanced Features
  mysql_db:
    config_file: /etc/my.cnf
    login_user: root
    login_password: 123456
    name: phpmyadmin
    state: import
    target: /data/apps/phpmyadmin/sql/create_tables.sql
  when: phpver != 54



- name: phpMyadmin own
  file: 
    path: /data/apps/phpmyadmin
    group: nginx
    owner: nginx
    recurse: yes
    state: directory

- name: nginx service restart
  service: name=nginx state=restarted

- name: PHP-FPM service restart
  service: name=php-fpm state=restarted


