---

- name: Create apps directory
  file: 
      path: /data/apps
      state: directory
      owner: nginx
      group: nginx

- name: Download 9panel
  git:
    repo: https://github.com/Websoft9/9panel.git
    dest: /data/apps/9panel

- name: Enable 9panel I
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: '"name":"LNMP","switch":0,'
    line: '"name":"LNMP","switch":1,'

- name: Set default site I
  shell: cp -rp /data/apps/9panel/*  /data/wwwroot/www.example.com

- name: Set default site II
  file:
    path: "/data/wwwroot/www.example.com/{{ item }}"
    state: absent
  with_items:
    - db.html
    - ftp.html
    - index.html
    - tools.html

- name: Set default site III
  command: mv /data/wwwroot/www.example.com/example.html /data/wwwroot/www.example.com/index.html


- name: Change apps directory Own
  file:
      path: /data/apps
      owner: nginx
      group: nginx
      recurse: yes
  notify: restart nginx
